### ISSUE TITLE
extra properties returned in response examples

### ISSUE THREAD

**Issue by moscicki** [cernbox/smashbox#47]
@dragotin: I think we have some bugs in our examples. I just want to make sure: the server should return ONLY the properties the client asks for, right? That's a sensible thing to specify. Or do we have some legacy behaviour in the sync client right now?

Specifically:

In Quota Check Call (https://github.com/cernbox/smashbox/blob/master/protocol/protocol.md#quota-check-call): we only ask for etag but we show a response with other properities. In addition there is this comment below the example: "Besides the actual quota sizes in bytes the server also returns the fileId and the permissions of the top directory."

Likewise for List Directory (https://github.com/cernbox/smashbox/blob/master/protocol/protocol.md#list-directory). We show that oc:size in the response but it is not part of the request.

**Comment by moscicki** [comment]
@dragotin: I will assume that these are just mistakes in the doc and will fix it so that requests and responses match.

**Comment by dragotin** [comment]
Hmm, good question. I _think_ I remember that the server sometimes returns more than it is asked for. @deepdiver1975 cna you elaborate on that?
