### ISSUE TITLE
OC-ASync header

### ISSUE THREAD

**Issue by moscicki** [cernbox/smashbox#55]
@dragotin: could you please elaborate a little bit on the meaning of this header for the sync protocol? Do you expect the server to behave and respond differently to client's request if this header is set?

**Comment by dragotin** [comment]
@ogoffart could you elaborate please

**Comment by ogoffart** [comment]
https://github.com/owncloud/core/issues/12097

(That was done for a specific customer who needed reliable upload of huge files. They have an app that support this protocol, but the normal ownCloud server does not support it)

**Comment by moscicki** [comment]
Okey. I don't find any trace of this being actually used by the client -- is this a dead feature in the current master branch already? So should I mark it as optional or obsolete in the doc?

I understand this as a solution for long-lasting operations which avoids problems with timeouts. It could be potentially interesting in the future I guess.

**Comment by dragotin** [comment]
No, its not dead, its just not implemented on our server. It's optional, but future releases might support it.

**Comment by moscicki** [comment]
Thanks for clarification.

**Comment by ogoffart** [comment]
It is in the client  in propagateupload.cpp  
(line 627 _item->_httpErrorCode == 202,   and all the PollJob stuff)
